# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choice1',
        ),
        migrations.RenameField(
            model_name='choice1',
            old_name='question',
            new_name='question1',
        ),
    ]
