# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170601_1324'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice1',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question1',
            new_name='question',
        ),
    ]
